name: Create ECR Image

on:
  push:
    branches: [ "deploy" ]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: 097669199623.dkr.ecr.us-east-2.amazonaws.com/petclinic     


jobs:
  ci:
    name: Creation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-session-name: github-actions-session


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      run: |
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    
    - name: Trigger infra repo workflow
      uses: peter-evans/repository-dispatch@v3
      env:
        IMAGE_TAG: ${{ github.sha }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
      with: 
        token: ${{ secrets.GO_TOKEN }}
        repository: AWS-TF-POC/infrastructure
        event-type: petclinic-ecs-rolling
        client-payload: |
          {
            "image_url": "${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          }